name: my_keycloak_project
services:
  postgres_kc:
    container_name: keycloak_postgres
    image: postgres:17-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak -p 5432"]
      interval: 10s      # Проверять каждые 10 секунд
      timeout: 5s        # Таймаут команды
      retries: 5         # 5 неудачных попыток = unhealthy
    restart: unless-stopped

  postgres_main:
    container_name: main_postgres
    image: postgres:17-bookworm
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: dotnetwebapi
      POSTGRES_PASSWORD: ${POSTGRES_MAIN_PASSWORD:-main}
    volumes:
      - main_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dotnetwebapi -d main -p 5432"]
      interval: 10s      # Проверять каждые 10 секунд
      timeout: 5s        # Таймаут команды
      retries: 5         # 5 неудачных попыток = unhealthy
    restart: unless-stopped

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:26.5.4-0
    command: start
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_kc:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: true
    depends_on:
      postgres_kc:
        condition: service_healthy  # Ждём готовности БД
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 2s
      timeout: 1s
      retries: 5  # Keycloak долго стартует
      start_period: 60s  # Даём время на первый запуск
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

volumes:
  keycloak_postgres_data:
  minio_data:
  main_postgres_data: